on:
  watch:
    types: started

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: echo "NEW_VERSION=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append
        
      - run: flutter config --no-analytics
      
      - run: dart --disable-analytics

      - name: Bump MyAppVersion in Inno Setup
        run: |
          (Get-Content -Path "inno-setup.iss") -replace '#define MyAppVersion "[\d\.]+"', "#define MyAppVersion `"${{ env.NEW_VERSION }}`"" | Set-Content -Path "inno-setup.iss"
        shell: pwsh
      
      - run: flutter gen-l10n

      - run: dart run build_runner build --delete-conflicting-outputs

      - run: flutter build windows --build-name=${{ env.NEW_VERSION }} --build-number=1
      
      - name: Build Installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "inno-setup.iss"
        shell: cmd

      - name: Calculate SHA256 hash
        run: |
          $hash = Get-FileHash "build/RevisionTool-Setup.exe" -Algorithm SHA256
          echo "SHA256_HASH=$($hash.Hash)" | Out-File -FilePath $env:GITHUB_ENV -Append
        
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: RevisionTool-Setup.exe
          path: build/RevisionTool-Setup.exe
